#!/usr/bin/env zsh

successfully() {
  $* || (echo "\nfailed" 1>&2 && exit 1)
}

fancy_echo() {
  echo "\n$1"
}

fancy_echo "Setting up Python ..."
  brew install python --framework

fancy_echo "Setting up updated VIm"
  brew install vim

fancy_echo "Setting up powerline ..."
  pip install --user git+git://github.com/Lokaltog/powerline

fancy_echo "Setting up SPF13"
 sh <(curl http://j.mp/spf13-vim3 -L)
